#!/bin/bash

killall -9 mysqld
cd $QEMU_MC/apps/mysql

# Start the server at port 7000 and sock file /tmp/mysql.sock
./mysql-install/libexec/mysqld --defaults-file=./my.cnf &
sleep 1;

# Run sysbench, with 2 threads.
./run-sysbench -p 7000 -t 4 -i 127.0.0.1
sleep 1;
killall -9 mysqld
