#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


#if [ -z $1 ]; then
#        # No version number
#        echo "Usage: <version number: e.g. 1.1.5>"
#        exit 1
#fi
VER=1.15.0
cd $QEMU_MC/apps/leveldb


#multi-line comments
:<<BLOCK
ROUTINE="--compress"
if [ $1"X" != "X" ];
then
        ROUTINE=$1
fi
BLOCK



APP=$QEMU_MC/apps/leveldb/db_bench
SENTENCEA=static\ int\ FLAGS_threads\ =\ 1\;
APPB=$QEMU_MC/apps/leveldb/db_bench_4
SENTENCEB=static\ int\ FLAGS_threads\ =\ 4\;
APPC=$QEMU_MC/apps/leveldb/db_bench_8
SENTENCEC=static\ int\ FLAGS_threads\ =\ 8\;
APPD=$QEMU_MC/apps/leveldb/db_bench_16
SENTENCED=static\ int\ FLAGS_threads\ =\ 16\;

SOURCE_FILE=$QEMU_MC/apps/leveldb/leveldb-$VER/db/db_bench.cc
echo $SOURCE_FILE


if [ ! -f db_bench ]; then
	pushd leveldb-$VER
	sed -i "70c$SENTENCEA" $SOURCE_FILE          #用$1替换69行的内容
	make all
	make db_bench
	mv db_bench ../db_bench
fi

#$APP > result

for i in $(seq 10); do
	$APP >  01_result_leveldb_${i}
	sleep 2
done

if [ ! -f db_bench_4 ]; then
	pushd leveldb-$VER
	sed -i "70c$SENTENCEB" $SOURCE_FILE          #用$1替换69行的内容
	make all
	make db_bench
	mv db_bench ../db_bench_4
fi

for i in $(seq 10); do
	$APPB > 04_result_leveldb_${i}
done

if [ ! -f db_bench_8 ]; then
	pushd leveldb-$VER
	sed -i "70c$SENTENCEC" $SOURCE_FILE          #用$1替换69行的内容
	make all
	make db_bench
	mv db_bench ../db_bench_8
fi

for i in $(seq 10); do
	$APPC > 08_result_leveldb_${i}
	sleep 2
done


if [ ! -f db_bench_16 ]; then
	pushd leveldb-$VER
	sed -i "70c$SENTENCED" $SOURCE_FILE          #用$1替换69行的内容
	make all
	make db_bench
	mv db_bench ../db_bench_16
fi

for i in $(seq 10); do
	$APPD > 16_result_leveldb_${i}
	sleep 2
done